name: Generate Daily Gaming Curiosity

on:
  schedule:
    # Ejecutar todos los días a las 6:00 AM UTC (2:00 AM EST, 8:00 AM CET)
    - cron: '*/10 * * * *'
  
  # Permitir ejecución manual desde GitHub UI
  workflow_dispatch:

jobs:
  generate-curiosity:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Instalar dependencias
        run: npm install --legacy-peer-deps

      - name: Generate New Curiosity
        env:
          SUPABASE_SERVICE_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY_SUPABASE }}
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_URL_SUPABASE }}
        run: |
          node scripts/script-new.js